# Global build settings
[build]
  base = "project/"
  command = "npm run build" # Standardize this unless you specifically need different commands
  publish = "project/dist" # Ensure this is correct based on your actual output directory

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[context.production]
  # Ensure the publish directory is consistent unless specifically needed
  publish = "dist"
  command = "npm run build" # Changed to standardize the build process across all contexts
  environment = { NODE_VERSION = "14.15.3" }

[context.deploy-preview]
  publish = "project/dist"

# Configuration for branch deploys
[context.branch-deploy]
  command = "npm run build" # Ensure all non-specific branches use a standard build command
  environment = { NODE_ENV = "development" }

[context.staging]
  command = "npm run build" # Standardize staging environment as well
  base = "staging"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"
  status = 301

[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 302
  force = true
  query = {id = ":id"}
  conditions = {Language = ["en"], Country = ["US"]}

[[redirects]]
  from = "/gated-path"
  to = "/login" # Example: Redirect to login if not an admin
  status = 302
  conditions = {Role = ["admin"]}
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions/"

[dev]
  command = "yarn start"
  port = 8888
  publish = "project/dist"
